# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "ubuntu/bionic64"
BOX_VERSION = "20230607.0.5"
MEMORY = 1024
CPUS = 1
MASTER = "lquehecS"
MASTER_IP = "192.168.56.110"
SLAVE = "lquehecSW"
SLAVE_IP = "192.168.56.111"
SHARED_FOLDER = "/vagrant/shared"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION

  config.vm.define MASTER do |control|
    control.vm.hostname = MASTER
    control.vm.network "private_network", ip: MASTER_IP
    control.vm.synced_folder "./shared", SHARED_FOLDER, type: "virtualbox", create: true
    control.vm.provider "virtualbox" do |v|
      v.name = MASTER
      v.memory =  MEMORY
      v.cpus = CPUS
      v.gui = false # Disable GUI
    end
    control.vm.provision "shell", path: "scripts/init-master-node.sh", env: {
      "MASTER_IP" => MASTER_IP,
      "SHARED_FOLDER" => SHARED_FOLDER,
    }
  end

  config.vm.define SLAVE do |control|
    control.vm.hostname = SLAVE
    control.vm.network "private_network", ip: SLAVE_IP
    control.vm.synced_folder "./shared", SHARED_FOLDER, type: "virtualbox", create: true
    control.vm.provider "virtualbox" do |v|
      v.name = SLAVE
      v.memory =  MEMORY
      v.cpus = CPUS
      v.gui = false # Disable GUI
    end
    control.vm.provision "shell", path: "scripts/init-slave-node.sh", env: {
      "MASTER_IP" => MASTER_IP,
      "SLAVE_IP" => SLAVE_IP,
      "SHARED_FOLDER" => SHARED_FOLDER,
    }
  end
end
