---
apiVersion: apps/v1
kind: Application
metadata:
  name: playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'myrepo' #TODO: replace with your repo URL
    targetRevision: HEAD
    path: playground
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---